# Generated by Django 6.0.2 on 2026-04-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='minecraftserver',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
